# Generated by Django 3.1.7 on 2021-03-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210316_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_feature',
            field=models.BooleanField(default=False, help_text='choose only one image to feature your product'),
        ),
    ]
